spring:
  application:
    name: agielelectronics_server
  datasource:
    url: jdbc:postgresql://localhost:5432/agile_electronics
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: my-kafka-streams-application
  flyway:
    url: jdbc:postgresql://localhost:5432/agilelectronics
    user: postgres
    password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: itugealex@gmail.com
    password: Admin@Acesoft1
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---

server:
  port: 8080
